### ISSUE TITLE
Bug: CSS module styles fail to apply when using trusted mode

### ISSUE THREAD

**Issue by calebjacob** [near/bos-web-engine#339] opened 2024-02-29 18:03 UTC
Bug Reproduction: https://bwe.near.dev/webengine.near/TrustedStyleBugParent

Open the following components in the sandbox:

- https://bwe.near.dev/webengine.near/TrustedStyleBugChild
- https://bwe.near.dev/webengine.near/TrustedStyleBugParent

When using `trust={{ mode: 'trusted-author' }}`, all CSS Module styles fail to apply in children (the child should have a green background). Styles work as expected when not using trust (sandboxed).

**Comment by calebjacob** [comment] 2024-02-29 18:07
Hey @mpeterdev, this is a potential blocker for this ticket: https://github.com/near/bos-web-engine/issues/296

We have a couple options:

1. Finish up my rework of the styles knowing that the trusted styles will be broken until this bug is resolved.
2. Use inline CSS styles where needed to make it look acceptable for now.

**Comment by mpeterdev** [comment] 2024-02-29 18:11
duplicate of #307

**Closed by mpeterdev** 2024-02-29 18:11 UTC
Labels: bug
